apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: node-02
        image: gcr.io/git-jbash-123/cldproxy:01
        imagePullPolicy: Always
        ports:
        - containerPort: 9981
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: secret-app-config
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-app-config 
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-app-config 
              key: password
      - name: cloudsql-proxy
         
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
        args:
          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          # - "--private-ip"

          # Enable structured logging with LogEntry format:
          - "--structured-logs"


          # Replace DB_PORT with the port the proxy should listen on
          - "--port=5432"
          - "git-jbash-123:us-central1:quickstart-instance"

        # [START cloud_sql_proxy_k8s_volume_mount]
          # This flag specifies where the service account key can be found
          - "--credentials-file=/home/quadri_muzammil999/cloudpsql/credentials.json"
        securityContext:
          # The default Cloud SQL Auth Proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        
        volumeMounts:
        - name: cloudsql-credentials
          mountPath: /home
          readOnly: true
      volumes:
      - name: cloudsql-credentials
        secret:
           secretName: gke-secret-sa 
  
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsservice
spec:
  type: LoadBalancer
  selector:
    app: nodejs
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 9981
