apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: muzammil # required field for kubernetes.io/basic-auth
  password: admin123 # required field for kubernetes.io/basic-auth
  dbname: clouddb 
